### ISSUE TITLE
Change website description, logo and title

### ISSUE THREAD

**Issue by Audacity21** [Audacity21/bz-lab-tracker#23]
Change the details here and change the website description so that it gets shown when this link is shared with other people. 

![image](https://github.com/Audacity21/bz-lab-tracker/assets/74983916/65cc9c56-1baa-4ef7-81e8-70ee4904723b)

**Comment by Vishalvirdi** [comment]
@Audacity21  Hi I would love to do it. What logo, description you guys want ? Can u explain a bit.

**Comment by Audacity21** [comment]
Hi Vishal!!

Linking some resources for you. 

This has to be the icon:
![image](https://github.com/Audacity21/bz-lab-tracker/assets/74983916/8323fd45-28cb-4fd0-94d8-029e828c8e2d)

Title should be: Lab Tracker

Description can be: Track and vizualise progress of students from mentorpick directly using the lab tracker. 

The description should be shown when you paste/share the link on whatsapp and telegram.

Good luck!! Lemme know if you face any issues.

**Comment by Vishalvirdi** [comment]
I have done logo, titile but for description I am not able to test it. Can please verify that description is correct ?. In case there is any problem please let me know. and I have created PR.

**Comment by Audacity21** [comment]
LGTM. Merged your code into main. Thanks for the contribution!!
